modLoader="javafml"
loaderVersion="[41,)"
license="MIT"
issueTrackerURL="https://github.com/GoryMoon/YouDied/issues"

[[mods]]
    modId="you_died"
    version="${file.jarVersion}"
    displayName="You Died"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/you-died"
    logoFile="logo.png"
    itemIcon="minecraft:netherite_sword"
    credits="Darkosto for feature request."
    authors="Gory_Moon"
    description='''
A mod that adds a Dark Souls inspired death screen'''

[[dependencies.you_died]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.you_died]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
